name: Build and test

on: pull_request

jobs:
  run-tests-job:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: latest-stable

      - name: Find iPhone Simulator UUID
        id: find-simulator
        run: |
          SIMULATOR_ID=$(xcrun simctl list devices available | grep "iPhone 14 Pro Max" | head -n 1 | awk -F '[()]' '{print $2}')
          echo "SIMULATOR_ID=$SIMULATOR_ID" >> $GITHUB_ENV

      - name: Build and test
        run: |
          xcodebuild test -project swift-sdk.xcodeproj \
            -scheme swift-sdk \
            -sdk iphonesimulator \
            -destination "id=${SIMULATOR_ID}" \
            -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}

      - name: CocoaPods lint
        run: pod lib lint

      - name: Upload coverage report to codecov.io
        run: bash <(curl -s https://codecov.io/bash) -X gcov -J 'IterableSDK' -J 'IterableAppExtensions'