name: Build and test

on: pull_request

jobs:
  run-tests-job:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Cleanup Simulators
        run: |
          xcrun simctl shutdown all || true
          xcrun simctl erase all || true
          xcrun simctl delete unavailable

      - name: Create and Boot Simulator
        run: |
          RUNTIME=$(xcrun simctl list runtimes | grep "iOS-17-0" | awk '{print $NF}')
          if [ -z "$RUNTIME" ]; then
            echo "Error: Required iOS runtime not found!" >&2
            exit 1
          fi
          xcrun simctl create "iPhone-14-Pro-Max-CI" "iPhone 14 Pro Max" "$RUNTIME"
          xcrun simctl boot "iPhone-14-Pro-Max-CI"

      - name: Verify Simulators
        run: xcrun simctl list devices

      - name: Get Simulator ID Dynamically
        id: get-simulator-id
        run: |
          SIMULATOR_ID=$(xcrun simctl list devices | grep "iPhone-14-Pro-Max-CI" | grep -oE '[A-F0-9-]{36}')
          echo "SIMULATOR_ID=$SIMULATOR_ID" >> $GITHUB_ENV

      - name: Build and test with parallel testing
        run: |
          xcodebuild test \
            -project swift-sdk.xcodeproj \
            -scheme swift-sdk \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,id=${SIMULATOR_ID}" \
            -enableCodeCoverage YES \
            -parallel-testing-enabled YES \
            -parallel-testing-worker-count 4 \
            -resultBundlePath TestResults.xcresult \
            CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}

      - name: CocoaPods lint
        run: pod lib lint

      - name: Upload coverage report to codecov.io
        run: bash <(curl -s https://codecov.io/bash) -X gcov -J 'IterableSDK' -J 'IterableAppExtensions'
 
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()
