name: Build and test

on: pull_request

jobs:
  run-tests-job:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: latest-stable

      - name: Cleanup Simulators
        run: |
          xcrun simctl shutdown all || true
          xcrun simctl erase all || true
          xcrun simctl delete unavailable
          RUNTIME=$(xcrun simctl list runtimes | grep "iOS" | grep -v unavailable | head -n 1 | awk '{print $1}')
          xcrun simctl create "iPhone-14-Pro-Max-CI" "iPhone 14 Pro Max" "$RUNTIME"

      - name: Verify Simulators
        run: xcrun simctl list devices

      - name: Boot Simulator
        run: |
          xcrun simctl boot "iPhone-14-Pro-Max-CI"

      - name: Build and test with parallel testing
        run: |
          xcodebuild test -project swift-sdk.xcodeproj \
            -scheme swift-sdk \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone-14-Pro-Max-CI' \
            -enableCodeCoverage YES \
            -parallel-testing-enabled YES \
            -parallel-testing-worker-count 4 \
            CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}

      - name: CocoaPods lint
        run: pod lib lint

      - name: Upload coverage report to codecov.io
        run: bash <(curl -s https://codecov.io/bash) -X gcov -J 'IterableSDK' -J 'IterableAppExtensions'