name: iOS SDK Release
run-name: ${{ github.actor }} is starting iOS SDK release

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: "iOS SDK version"
        required: true
      changelog_section:
        description: "Changelog version header (e.g. 6.4.17, 6.5.0-beta)"

jobs:
  ios-sdk-release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: set version number and push podspecs to git
        run: bundle exec fastlane ios bump_release_version version:${{ github.event.inputs.version_number }}

      - name: clean cocaopods cache and lint
        run: bundle exec fastlane ios clean_and_lint

      - name: create xcframeworks and zip
        run: bundle exec fastlane ios build_xcframework output_dir:./output_dir

      - name: create github release and upload assets
        run: |
          bundle exec fastlane ios create_release version:${{ github.event.inputs.version_number }} \
          changelog_section:${{ github.event.inputs.changelog_section }} \
          output_dir:./output_dir \
          github_token:${{ secrets.GITHUB_TOKEN }}

      - name: push pods to trunk
        run: bundle exec fastlane ios pod_trunk_push
